// 定义主要的图标库及其前缀，包括io5
export const iconLibraries =
  process.env.NODE_ENV === 'production'
    ? []
    : [
        {
          name: 'Ant Design Icons',
          prefix: 'Ai',
          importPath: 'react-icons/ai',
          import: () => import('react-icons/ai'),
        },
        {
          name: 'Bootstrap Icons',
          prefix: 'Bs',
          importPath: 'react-icons/bs',
          import: () => import('react-icons/bs'),
        },
        {
          name: 'BoxIcons',
          prefix: 'Bi',
          importPath: 'react-icons/bi',
          import: () => import('react-icons/bi'),
        },
        {
          name: 'Circum Icons',
          prefix: 'Ci',
          importPath: 'react-icons/ci',
          import: () => import('react-icons/ci'),
        },
        {
          name: 'css.gg',
          prefix: 'Cg',
          importPath: 'react-icons/cg',
          import: () => import('react-icons/cg'),
        },
        {
          name: 'Devicons',
          prefix: 'Di',
          importPath: 'react-icons/di',
          import: () => import('react-icons/di'),
        },
        {
          name: 'Feather Icons',
          prefix: 'Fi',
          importPath: 'react-icons/fi',
          import: () => import('react-icons/fi'),
        },
        {
          name: 'Flat Color Icons',
          prefix: 'Fc',
          importPath: 'react-icons/fc',
          import: () => import('react-icons/fc'),
        },
        {
          name: 'Font Awesome 5',
          prefix: 'Fa',
          importPath: 'react-icons/fa',
          import: () => import('react-icons/fa'),
        },
        {
          name: 'Font Awesome 6',
          prefix: 'Fa',
          importPath: 'react-icons/fa6',
          import: () => import('react-icons/fa6'),
        },
        {
          name: 'Game Icons',
          prefix: 'Gi',
          importPath: 'react-icons/gi',
          import: () => import('react-icons/gi'),
        },
        {
          name: 'Github Octicons icons',
          prefix: 'Go',
          importPath: 'react-icons/go',
          import: () => import('react-icons/go'),
        },
        {
          name: 'Grommet-Icons',
          prefix: 'Gr',
          importPath: 'react-icons/gr',
          import: () => import('react-icons/gr'),
        },
        {
          name: 'Heroicons',
          prefix: 'Hi',
          importPath: 'react-icons/hi',
          import: () => import('react-icons/hi'),
        },
        {
          name: 'Heroicons 2',
          prefix: 'Hi',
          importPath: 'react-icons/hi2',
          import: () => import('react-icons/hi2'),
        },
        {
          name: 'IcoMoon Free',
          prefix: 'Im',
          importPath: 'react-icons/im',
          import: () => import('react-icons/im'),
        },
        {
          name: 'Icons8 Line Awesome',
          prefix: 'Lia',
          importPath: 'react-icons/lia',
          import: () => import('react-icons/lia'),
        },
        {
          name: 'Ionicons 4',
          prefix: 'Io',
          importPath: 'react-icons/io',
          import: () => import('react-icons/io'),
        },
        {
          name: 'Ionicons 5',
          prefix: 'Io',
          importPath: 'react-icons/io5',
          import: () => import('react-icons/io5'),
        },
        {
          name: 'Lucide',
          prefix: 'Lu',
          importPath: 'react-icons/lu',
          import: () => import('react-icons/lu'),
        },
        {
          name: 'Material Design icons',
          prefix: 'Md',
          importPath: 'react-icons/md',
          import: () => import('react-icons/md'),
        },
        {
          name: 'Phosphor Icons',
          prefix: 'Pi',
          importPath: 'react-icons/pi',
          import: () => import('react-icons/pi'),
        },
        {
          name: 'Radix Icons',
          prefix: 'Rx',
          importPath: 'react-icons/rx',
          import: () => import('react-icons/rx'),
        },
        {
          name: 'Remix Icons',
          prefix: 'Ri',
          importPath: 'react-icons/ri',
          import: () => import('react-icons/ri'),
        },
        {
          name: 'Simple Icons',
          prefix: 'Si',
          importPath: 'react-icons/si',
          import: () => import('react-icons/si'),
        },
        {
          name: 'Simple Line Icons',
          prefix: 'Sl',
          importPath: 'react-icons/sl',
          import: () => import('react-icons/sl'),
        },
        {
          name: 'Tabler Icons',
          prefix: 'Tb',
          importPath: 'react-icons/tb',
          import: () => import('react-icons/tb'),
        },
        {
          name: 'Themify Icons',
          prefix: 'Tfi',
          importPath: 'react-icons/tfi',
          import: () => import('react-icons/tfi'),
        },
        {
          name: 'Typicons',
          prefix: 'Ti',
          importPath: 'react-icons/ti',
          import: () => import('react-icons/ti'),
        },
        {
          name: 'VS Code Icons',
          prefix: 'Vsc',
          importPath: 'react-icons/vsc',
          import: () => import('react-icons/vsc'),
        },
        {
          name: 'Weather Icons',
          prefix: 'Wi',
          importPath: 'react-icons/wi',
          import: () => import('react-icons/wi'),
        },
      ];
